/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.codideep.app.presentationlayer.person;

import com.codideep.app.businesslayer.BusinessPerson;
import com.codideep.app.datatransferlayer.DtoPerson;
import javax.swing.table.DefaultTableModel;
import java.util.List;

/**
 *
 * @author KAAF0
 */
public class FrmPersonGetAll extends javax.swing.JInternalFrame {

    private final BusinessPerson businessPerson;
    private final DefaultTableModel dtmPerson;

    /**
     * Creates new form FrmPersonGetAll
     */
    public FrmPersonGetAll() {
        businessPerson = new BusinessPerson();

        initComponents();

        dtmPerson = new DefaultTableModel();

        dtmPerson.addColumn("DNI");
        dtmPerson.addColumn("Nombre");
        dtmPerson.addColumn("Apellido");
        dtmPerson.addColumn("Fecha de nacimiento");
        dtmPerson.addColumn("Género");
        dtmPerson.addColumn("Registro");
        dtmPerson.addColumn("Actualización");

        tablePerson.setModel(dtmPerson);

        List<DtoPerson> listDtoPerson = businessPerson.getAll();

        for (DtoPerson item : listDtoPerson) {
            dtmPerson.addRow(new Object[] {
                item.getDni(),
                item.getFirstName(),
                item.getSurName(),
                item.getBirthDate(),
                item.isGender() ? "Masculino" : "Femenino",
                item.getCreatedAt(),
                item.getUpdatedAt()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablePerson = new javax.swing.JTable();

        tablePerson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablePerson);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 701, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablePerson;
    // End of variables declaration//GEN-END:variables
}
